/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_crashcapture_NativeCrashCapture */

#ifndef _Included_com_crashcapture_NativeCrashCapture
#define _Included_com_crashcapture_NativeCrashCapture
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_crashcapture_NativeCrashCapture
 * Method:    nativeInit
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint

JNICALL Java_com_disasterrecovery_jnicrash_NativeCrashCapture_nativeInit
        (JNIEnv *, jobject, jstring);

/*
 * Class:     com_crashcapture_NativeCrashCapture
 * Method:    nativeCrash
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint

JNICALL Java_com_disasterrecovery_jnicrash_NativeCrashCapture_nativeCrash
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
